version: 0.1

# http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html#sample-docker-dir

# http://www.awsomeblog.com/aws-elasticbeanstalk-multicontainer-docker-deployment-with-aws-codebuild/#

environment_variables:
  plaintext:
    some_env_value: "some_value"

phases:
  pre_build:
    commands:
      - sudo apt-get -y update
      - sudo apt-get -y install docker.io
      - sudo apt-get -y install python-pip
      - sudo apt-get -y install python3-pip
      - pip install --upgrade --user awscli
      - pip install --upgrade --user boto3
    	- docker info
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo pre build completed on: `date`
	build:
    commands:
      - echo build started on: `date`
			- docker build --rm=false -f Dockerfile_hello -t rnzaws/hello .
			- docker images
			- docker tag rnzaws/hello:ebtest 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest
			- docker push 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest
      - echo build completed on: `date`
  post_build:
    commands:
      - echo post build completed on: `date`

artifacts:
  files:
    - Dockerrun.aws.json
  discard-paths: yes
  base-directory: ./
