version: 0.1

environment_variables:
  plaintext:
    some_env_value: "some_value"

phases:
  install:
    commands:
      - sudo apt-get -y update
      - sudo apt-get -y install zip unzip
      - pip install --upgrade pip

      - pip install boto3
  pre_build:
    commands:
      - command
      - command
  build:
    commands:
      - echo Build started on `date`
      - zip -r app.zip * -x *.git*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.zip
  discard-paths: yes
  base-directory: location
