---
version: 0.1

environment_variables:
  plaintext:
    some_env_value: "some_value"

phases:
  pre_build:
    commands:
      - whoami
      - docker info
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo pre build completed on `date`
  build:
    commands:
      - echo build started on `date`
      - docker build --rm=false -f Dockerfile_web -t rnzaws/web .
      - docker build --rm=false -f Dockerfile_processor -t rnzaws/processor .
      - echo build completed on `date`
  post_build:
    commands:
      - echo post_build started on `date`
      - docker images
      - docker tag rnzaws/web:latest 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest
      - docker push 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest
      - docker tag rnzaws/processor:latest 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest-processor
      - docker push 702786411213.dkr.ecr.us-east-1.amazonaws.com/test:ebtest-processor
      - echo post_build completed on `date`

artifacts:
  files:
    - Dockerrun.aws.json
  discard-paths: 'yes'
  base-directory: ./

